In [2]:
import torch

## Initalization

In [3]:
# empty tensor
torch.empty(size=(3,3,3)) # size

tensor([[[1.8990e+28, 2.9602e+29, 7.1447e+31],
         [2.2266e-15, 4.5155e+27, 5.4965e+22],
         [7.9325e+34, 1.8672e+25, 1.2709e+31]],

        [[4.4374e+27, 5.3992e-14, 1.3556e-19],
         [4.5155e+27, 5.4965e+22, 7.9325e+34],
         [7.5555e+31, 1.2705e+31, 7.0948e+22]],

        [[2.4176e-12, 7.5555e+31, 7.9309e+34],
         [1.4603e-19, 1.8617e+25, 1.1835e+22],
         [4.3066e+21, 7.3867e+20, 2.0027e-19]]])

In [4]:
# from list
torch.tensor([1,2,3,4,5])

tensor([1, 2, 3, 4, 5])

In [5]:
# random tensor
torch.rand(size=(2,2))

tensor([[0.7355, 0.5699],
        [0.9219, 0.2381]])

In [6]:
# values
x = torch.ones(size=(3,3), dtype=torch.float16)


In [7]:
# properties
print(x)
print(x.size())

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float16)
torch.Size([3, 3])


## Operations

In [8]:
x = torch.rand(2,2)
y = torch.ones(2,2)

z = x+y
z = torch.add(x,y) # equilalent
 
y.add_(x) # trailing underscor will do **inplace** modification

print(y)
y==z

tensor([[1.3426, 1.2864],
        [1.5865, 1.3611]])


tensor([[True, True],
        [True, True]])

In [9]:
import numpy as np
a = torch.ones(5)
b = a.numpy() # convert to numpy

In [10]:
torch.cuda.is_available()

False